### ISSUE TITLE
REST

### ISSUE THREAD

**Issue by sergioviera** [dds-frd-utn/TP3-SharkBank-Grupo1#2]
Sería bueno hacer al menos una llamada al GET. El formato de mocky, es igual al JSON que devuelve el REST del TP1?

https://github.com/dds-frd-utn/TP3-SharkBank-Grupo1/blob/fd85f2d3b27459939def409a9986f71b831aea04/app/src/main/java/ads/sharkbankapp/MainScreen.java#L168

**Comment by daviddonayo** [comment]
Ahi agregué la dirección de rest del cliente id = 5
